version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  versioning-strategy: increase
  ignore:
  - dependency-name: socket.io-client
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@sentry/node"
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
  - dependency-name: sequelize
    versions:
    - 6.4.0
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: nodemailer
    versions:
    - 6.4.18
  - dependency-name: commander
    versions:
    - 7.0.0
    - 7.1.0
  - dependency-name: rotating-file-stream
    versions:
    - 2.1.4
  - dependency-name: sqlite3
    versions:
    - 5.0.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
  - web-ui
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: socket.io-client
    versions:
    - ">= 4.a, < 5"
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: rxjs-compat
    versions:
    - 6.6.6
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: tslib
    versions:
    - 2.1.0
